# Generated by Django 5.2.17 on 2026-08-27 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criador',
            fields=[
                ('id_criador', models.AutoField(primary_key=True, serialize=False)),
                ('nome_criador', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id_fase', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fase', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nome_nivel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id_personagem', models.AutoField(primary_key=True, serialize=False)),
                ('nome_personagem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id_plataforma', models.AutoField(primary_key=True, serialize=False)),
                ('nome_plataforma', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id_servidor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_servidor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id_jogo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_jogo', models.CharField(max_length=200)),
                ('id_criador', models.ForeignKey(blank=True, db_column='id_criador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jogoapp.criador')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_jogo',
            fields=[
                ('id_nivel_jogo', models.AutoField(primary_key=True, serialize=False)),
                ('id_jogo', models.ForeignKey(blank=True, db_column='id_jogo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jogoapp.jogo')),
                ('id_nivel', models.ForeignKey(blank=True, db_column='id_nivel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jogoapp.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma_jogo',
            fields=[
                ('id_plataforma_jogo', models.AutoField(primary_key=True, serialize=False)),
                ('id_jogo', models.ForeignKey(blank=True, db_column='id_jogo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jogoapp.jogo')),
                ('id_plataforma', models.ForeignKey(blank=True, db_column='id_plataforma', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jogoapp.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor_jogo',
            fields=[
                ('id_servidor_jogo', models.AutoField(primary_key=True, serialize=False)),
                ('id_jogo', models.ForeignKey(blank=True, db_column='id_jogo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jogoapp.jogo')),
                ('id_servidor', models.ForeignKey(blank=True, db_column='id_servidor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jogoapp.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_jogo',
            fields=[
                ('id_usuario_jogo', models.AutoField(primary_key=True, serialize=False)),
                ('id_jogo', models.ForeignKey(blank=True, db_column='id_jogo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jogoapp.jogo')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jogoapp.usuario')),
            ],
        ),
    ]
